[package]
name = "techmino-replay-toolkit"
version = "0.1.0"
edition = "2021"
description = "A serializer and deserializer for Techmino replays"
repository = "https://github.com/techmino-hub/techmino-replay-toolkit-rs"
license = "GPL-3.0-or-later"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn" }
alloc_instead_of_core = { level = "warn" }
std_instead_of_alloc = { level = "warn" }
std_instead_of_core = { level = "warn" }

[features]
default = ["std"]
std = ["serde/std"]
alloc = []

[dependencies]
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.17.1", default-features = false, features = [
    "alloc",
    "default-hasher",
    "serde",
] }
miniz_oxide = { version = "0.9.1", default-features = false, features = [
    "alloc",
    "serde",
    "simd",
    "with-alloc",
] }
semver = { version = "1.0.25", default-features = false, features = ["serde"] }
serde = { version = "1.0.214", features = [
    "alloc",
    "derive",
], default-features = false }
serde_json = { version = "1.0.132", default-features = false, features = [
    "alloc",
] }

[dev-dependencies]
ron = "0.12.1"
