[workspace]

resolver = "3"
members = ["lib", "lib/fuzz", "vlq"]

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn" }
alloc_instead_of_core = { level = "warn" }
std_instead_of_alloc = { level = "warn" }
std_instead_of_core = { level = "warn" }

[workspace.lints.rustdoc]
unescaped_backticks = "deny"

[package]
name = "techmino-replay-toolkit"
version = "0.1.0"
edition = "2024"
description = "An all-in-one binary containing tools for Techmino replays"
repository = "https://github.com/techmino-hub/techmino-replay-toolkit-rs"
license = "GPL-3.0-or-later"
keywords = ["techmino"]
publish = false
rust-version = "1.96"
build = "trt_build.rs"

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
incremental = false
debug = "line-tables-only"
# strip = true

[features]
default = ["tui"]
gui = ["dep:slint"]
tui = ["dep:ratatui", "dep:miniz_oxide", "dep:dirs"]

[dependencies]
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
dirs = { version = "5.0", optional = true }
libtechmino-replay = { version = "0.1.0", features = ["preserve_metadata_order", "float_roundtrip"]}
miniz_oxide = { version = "0.9.1", optional = true }
ratatui = { version = "0.30.2", optional = true }
serde = "1.0.228"
serde_json = "1.0.150"
slint = { version = "1.17.1", optional = true }
thiserror = "2.0.18"

[dev-dependencies]
fastrand = "2.5.0"
