[package]
name = "libtechmino-replay"
version = "0.1.0"
edition = "2021"
description = "A serializer and deserializer for Techmino replays"
repository = "https://github.com/techmino-hub/techmino-replay-toolkit-rs"
license = "GPL-3.0-or-later"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn" }
alloc_instead_of_core = { level = "warn" }
std_instead_of_alloc = { level = "warn" }
std_instead_of_core = { level = "warn" }

[features]
# Either std or alloc must be enabled, but not both
default = ["std"]
# Either std or alloc must be enabled, but not both
std = ["serde/std", "strum/std", "thiserror/std"]
# Either std or alloc must be enabled, but not both
alloc = []
# Adds strum utilities for certain enums
strum = ["dep:strum"]

[dependencies]
libtechmino-vlq = { path = "../vlq" }
ascii = { version = "1.1.0", default-features = false, features = ["alloc"] }
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.17.1", default-features = false, features = [
    "alloc",
    "default-hasher",
    "serde",
] }
miniz_oxide = { version = "0.9.1", default-features = false, features = [
    "alloc",
    "serde",
    "simd",
    "with-alloc",
] }
semver = { version = "1.0.25", default-features = false, features = ["serde"] }
serde = { version = "1.0.214", features = [
    "alloc",
    "derive",
], default-features = false }
serde_json = { version = "1.0.132", default-features = false, features = [
    "alloc",
] }
strum = { version = "0.28.0", optional = true, default-features = false, features = [
    "derive",
] }
thiserror = { version = "2.0.18", default-features = false }

[dev-dependencies]
fastrand = "2.4.1"
ron = "0.12.1"

[[test]]
name = "streaming_roundtrip"

[[test]]
name = "roundtrip_noop"

[[test]]
name = "deser_data_match"
