[package]
name = "libtechmino-vlq"
version = "0.1.0"
edition = "2021"
description = "VLQ state machines for use in `libtechmino-replay`"
repository = "https://github.com/techmino-hub/techmino-replay-toolkit-rs"
license = "GPL-3.0-or-later"
keywords = ["techmino", "parser", "vlq"]
categories = ["no-std", "parser-implementations"]
include = ["/src", "/README.md"]

[lints]
workspace = true

[features]
std = ["thiserror/std"]

[dependencies]
thiserror = { version = "2.0.18", default-features = false }

[dev-dependencies]
fastrand = "2.4.1"
